#!/bin/sh

set -x

EXISTED=$(nmcli | grep bond0)
if [ -n "$EXISTED" ]; then
    echo "clear bond0"
    for I in 1 2 3; do
        sudo nmcli connection delete slave$I
    done
    sudo nmcli connection delete bond0
    sudo systemctl restart NetworkManager
    exit 0
fi

# sudo nmcli connection add type bond con-name bond0 mode active-backup ipv4.method manual ipv4.addresses 10.196.20.228/25 ipv4.gateway 10.196.20.129 ipv4.dns 127.0.0.1 ipv6.method disabled
sudo nmcli connection add type bond con-name bond0 ifname bond0 mode balance-alb \
    ipv4.method manual ipv4.addresses 10.196.20.228/25 ipv4.gateway 10.196.20.129 ipv4.dns 127.0.0.1 ipv6.method disabled

INDEX=1
for DEVNAME in $@; do
    echo "add $DEVNAME"
    sudo nmcli connection add con-name slave$INDEX ifname $DEVNAME type ethernet master bond0
    sudo nmcli connection up slave$INDEX
    INDEX=$((INDEX+1))
done

sudo nmcli connection down bond0
sudo nmcli connection up bond0

sudo systemctl restart NetworkManager
